DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    credit DEC(15,2) NOT NULL,
    currency varchar(20) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO accounts(name,credit, currency)
VALUES('Nikolina1',1000, 'RUB');

INSERT INTO accounts(name,credit, currency)
VALUES('Nikolina2',1000, 'RUB');

INSERT INTO accounts(name,credit, currency)
VALUES('Nikolina3',1000, 'RUB');

-- create transaction t1
Begin TRANSACTION ;

-- retrieve 500 rubles from account 1
UPDATE accounts
SET credit = credit - 500
where id = 1;

-- send them to account 2
UPDATE accounts
SET credit = credit + 500
where id = 3;

-- commit transaction t1
SAVEPOINT t1;

-- start commit t2
Begin TRANSACTION;

-- retrieve 700 rubles from account 2
UPDATE accounts
SET credit = credit - 700
where id = 2;

-- send them to account 2
UPDATE accounts
SET credit = credit + 700
where id = 1;

SAVEPOINT t2;


-- begin transaction t3
BEGIN TRANSACTION ;

-- retrieve 500 rubles from account 2
UPDATE accounts
SET credit = credit - 100
where id = 2;
-- send them to account 2

UPDATE accounts
SET credit = credit + 100
where id = 3;

SAVEPOINT t3;

-- this roll back does not change anything
ROLLBACK to savepoint t3;
SELECT * from accounts;

-- return to the state before the 3rd transaction
ROLLBACK to savepoint t2;
SELECT * from accounts;

-- return to the state before the 2nd transaction
ROLLBACK  to savepoint t1;
SELECT * from accounts;

-- -- return to the state before the 3rd transaction
ROLLBACK;

SELECT * from accounts;

COMMIT;